package main

import (
	"fmt"
	"github.com/stevzhang01/go-learning/intset"
)

func main() {
	var x, y intset.IntSet
	x.Add(1)
	x.Add(144)
	x.Add(9)
	fmt.Println(x.String())
	y.Add(9)
	y.Add(42)
	fmt.Println(y.String())
	x.UnionWith(&y)
	fmt.Println(x.String())
	fmt.Println(x.Has(9), x.Has(123))
	fmt.Println(&x)
	fmt.Println(x.String())
	fmt.Println((&x).String())
	fmt.Println(x)
	fmt.Println("test Len()")
	fmt.Println(x.Len())
	fmt.Println("test Remove()")
	x.Remove(9)
	fmt.Println(x.String())
	fmt.Println("test Clear()")
	x.Clear()
	fmt.Println(x.String())
	fmt.Println("test Copy()")
	x.Add(1)
	x.Add(44)
	x.Add(9)
	fmt.Println("x: ", x.String())
	c := x.Copy()
	fmt.Println("c: ", c.String())
	c.Remove(9)
	fmt.Println("x: ", x.String())
	fmt.Println("c: ", c.String())
	c.Add(11)
	fmt.Println("c: ", c.String())
	c.Add(15)
	fmt.Println("c: ", c.String())
	c.Add(89)
	c.Add(150)
	fmt.Println("c: ", c.String())
	fmt.Println("x: ", x.String())
	fmt.Println("test AddAll()")
	x.AddAll(15, 78, 99, 66, 190)
	fmt.Println("x: ", x.String())
	fmt.Println("c: ", c.String())
	ints := []int{579, 32, 11, 99, 89}
	x.AddAll(ints...)
	fmt.Println("x: ", x.String())
	fmt.Println("test Intersec()")
	inter := x.Intersec(c)
	fmt.Println("inter: ", inter.String())
	fmt.Println("test Diff()")
	diff := x.Diff(c)
	fmt.Println("diff: ", diff.String())
	fmt.Println("test SymDiff()")
	symdiff := x.SymDiff(c)
	fmt.Println("symdiff: ", symdiff)
	fmt.Println("test Elems()")
	elems := x.Elems()
	fmt.Println("elems: ", elems)
}
